id: I5024A1B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:23:48+00:00'
last_modified: '2022-06-09T04:53:15.596287+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1220
  title: ལྟ་བའི་དོགས་གཅོད་མཁས་པའི་སྙིང་གཏམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8576':
      image_group_id: I1CZ1681
      title: Volume 1 of lta ba'i dogs gcod mkhas pa'i snying gtam
      total_pages: 28
      order: 1
      base_file: 8576.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
