id: P008155
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1220
  title: ལྟ་བའི་དོགས་གཅོད་མཁས་པའི་སྙིང་གཏམ
  author: ''
  volumes:
    87000759921540f09fa9f4493ab9b25d:
      image_group_id: I1CZ1681
      title: ''
      volume_number: 1
      total_pages: 28
ebook_metadata:
  title: ལྟ་བའི་དོགས་གཅོད་མཁས་པའི་སྙིང་གཏམ
  author: ''
  sku: P008155
  cover: cover.jpg
  layers:
  - pagination
