id: P008155
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:05:02.182494
source_metadata:
  id: bdr:W1CZ1220
  title: ལྟ་བའི་དོགས་གཅོད་མཁས་པའི་སྙིང་གཏམ
  author: ''
  volumes:
    1c0456204e0b4e64a788911a0c8731db:
      image_group_id: I1CZ1681
      title: Volume 1 of lta ba'i dogs gcod mkhas pa'i snying gtam
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
